name: Build and Push Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
  IMAGE_NAME: lulapay-identityserver4
  DOTNET_VERSION: '3.1.x'
  PROJECT_PATH: 'src/IdentityServer'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install OpenSSL 1.1
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/IdentityServer.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/IdentityServer.csproj

    - name: Build application
      run: dotnet build ${{ env.PROJECT_PATH }}/IdentityServer.csproj --configuration Release --no-restore

    - name: Run tests
      run: |
        # Run tests if test projects exist
        if ls tests/**/*.csproj 1> /dev/null 2>&1; then
          dotnet test --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
        else
          echo "No test projects found, skipping tests"
        fi

    - name: Publish application
      run: dotnet publish ${{ env.PROJECT_PATH }}/IdentityServer.csproj --configuration Release --no-build --output ./publish

    - name: Get version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish/
        retention-days: 7

    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage
        path: ./coverage/**/coverage.cobertura.xml
        retention-days: 30

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/lulapay-identityserver4:latest
          ${{ env.REGISTRY }}/lulapay-identityserver4:${{ github.sha }}
        build-args: |
          VERSION=3.1-alpine